-- ============================================================
-- ROCAGENTINSIGHT — FONDASI STRUKTUR SNOWFLAKE
-- Dibuat untuk: Cortex Agent "RocAgentInsight" (analisa data
-- operasional RocAgent — execution logs, tool usage, error rate)
-- ============================================================

USE ROLE SECURITYADMIN;

-- ---- 1. ROLE hierarchy dedicated untuk RocAgentInsight ----
-- Dipisah dari ACCOUNTADMIN sehari-hari: role ini hanya punya
-- akses ke database/schema RocAgentInsight, bukan seluruh akun.
CREATE ROLE IF NOT EXISTS ROCAGENTINSIGHT_ADMIN
  COMMENT = 'Full control atas database/schema/warehouse RocAgentInsight';

CREATE ROLE IF NOT EXISTS ROCAGENTINSIGHT_ANALYST
  COMMENT = 'Read-only + Cortex Agent usage untuk analisa data RocAgent';

-- Hierarki: ACCOUNTADMIN > ROCAGENTINSIGHT_ADMIN > ROCAGENTINSIGHT_ANALYST
GRANT ROLE ROCAGENTINSIGHT_ANALYST TO ROLE ROCAGENTINSIGHT_ADMIN;
GRANT ROLE ROCAGENTINSIGHT_ADMIN TO ROLE SYSADMIN;
GRANT ROLE ROCAGENTINSIGHT_ADMIN TO USER IVANSSLO;
GRANT ROLE ROCAGENTINSIGHT_ANALYST TO USER IVANSSLO;

USE ROLE SYSADMIN;

-- ---- 2. WAREHOUSE dedicated (terpisah dari COMPUTE_WH default) ----
-- X-Small + auto-suspend 60s: workload analitik ringan/sesekali,
-- biaya minimal saat idle.
CREATE WAREHOUSE IF NOT EXISTS ROCAGENTINSIGHT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse dedicated untuk RocAgentInsight Cortex Agent & analisa data RocAgent';

GRANT USAGE ON WAREHOUSE ROCAGENTINSIGHT_WH TO ROLE ROCAGENTINSIGHT_ADMIN;
GRANT OPERATE ON WAREHOUSE ROCAGENTINSIGHT_WH TO ROLE ROCAGENTINSIGHT_ADMIN;
GRANT USAGE ON WAREHOUSE ROCAGENTINSIGHT_WH TO ROLE ROCAGENTINSIGHT_ANALYST;

-- ---- 3. DATABASE & SCHEMA ----
CREATE DATABASE IF NOT EXISTS ROCAGENTINSIGHT_DB
  COMMENT = 'Database fondasi untuk data operasional RocAgent (execution logs, tool usage, dsb) dan Cortex Agent RocAgentInsight';

GRANT OWNERSHIP ON DATABASE ROCAGENTINSIGHT_DB TO ROLE ROCAGENTINSIGHT_ADMIN COPY CURRENT GRANTS;

USE ROLE ROCAGENTINSIGHT_ADMIN;
USE DATABASE ROCAGENTINSIGHT_DB;

-- RAW: staging area, data mentah masuk apa adanya dari db.json/export RocAgent
CREATE SCHEMA IF NOT EXISTS RAW
  COMMENT = 'Staging: data mentah operasional RocAgent (belum dibersihkan/dimodelkan)';

-- ANALYTICS: tabel yang sudah dimodelkan, dipakai semantic model & Cortex Agent
CREATE SCHEMA IF NOT EXISTS ANALYTICS
  COMMENT = 'Data termodelkan untuk Cortex Agent RocAgentInsight (fact/dim tables, semantic views)';

-- GOVERNANCE: metadata, semantic model YAML/definitions, audit
CREATE SCHEMA IF NOT EXISTS GOVERNANCE
  COMMENT = 'Semantic model definitions, Cortex Agent config, audit trail';

GRANT USAGE ON DATABASE ROCAGENTINSIGHT_DB TO ROLE ROCAGENTINSIGHT_ANALYST;
GRANT USAGE ON SCHEMA ROCAGENTINSIGHT_DB.RAW TO ROLE ROCAGENTINSIGHT_ANALYST;
GRANT USAGE ON SCHEMA ROCAGENTINSIGHT_DB.ANALYTICS TO ROLE ROCAGENTINSIGHT_ANALYST;
GRANT USAGE ON SCHEMA ROCAGENTINSIGHT_DB.GOVERNANCE TO ROLE ROCAGENTINSIGHT_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ROCAGENTINSIGHT_DB.ANALYTICS TO ROLE ROCAGENTINSIGHT_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ROCAGENTINSIGHT_DB.ANALYTICS TO ROLE ROCAGENTINSIGHT_ANALYST;

-- Verifikasi
SHOW ROLES LIKE 'ROCAGENTINSIGHT%';
SHOW WAREHOUSES LIKE 'ROCAGENTINSIGHT%';
SHOW DATABASES LIKE 'ROCAGENTINSIGHT%';
SHOW SCHEMAS IN DATABASE ROCAGENTINSIGHT_DB;
